{{- if .Values.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsgenie-marid.fullname" . }}
  labels:
{{ include "opsgenie-marid.labels" . | indent 4 }}
data:
{{ toYaml .Values.configmap | indent 2 }}
{{- end }}
