{{- if .Values.gitSync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsgenie-marid.fullname" . }}-sshkey
  labels:
{{ include "opsgenie-marid.labels" . | indent 4 }}
data:
  ssh: {{ .Values.gitSync.sshKey | b64enc }}
  known_hosts: {{ .Values.gitSync.knownHosts | b64enc }}
{{- end }}
