apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dependency-track.fullname" . }}
  labels:
{{ include "dependency-track.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.configmap }}
{{ $key | indent 2 }}: |-
{{ $value | indent 4}}
{{- end -}}
