{{- if .Values.persistentVolume.enabled -}}
{{- if not .Values.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
  name: {{ template "dependency-track.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
{{- with .Values.persistentVolume.storageClass }}
  storageClassName: "{{ . }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}"
{{- end -}}
{{- end -}}
