name: "Publish charts to repo"
on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0
      with:
        charts_dir: charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
