name: "Test using kind and chart-testing tool"
on: [pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: ["v1.13.12", "v1.16.3"]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
    - name: Install kind
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: "v0.6.0"
        image: "kindest/node:${{ matrix.kubernetesVersion }}"
        config: kind-config.yaml
    - name: Verify kind
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl cluster-info
        kubectl get nodes -o wide
        kubectl get pods -n kube-system
    - uses: davidkarlsen/chart-testing-action@master
      #uses: helm/chart-testing-action@v1
      with:
        command: lint-and-install
